repos:
  - repo: https://github.com/psf/black
    rev: <version>
    hooks:
      - id: black
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: <version>
    hooks:
      - id: check-json
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: <version>
    hooks:
      - id: prettier
    files: \.(json|markdown|md|yaml|yml)$
repos:
  - repo: https://github.com/eslint/eslint
    rev: <version>
    hooks:
      - id: eslint
        name: eslint
        entry: eslint
        language: system
        types: [vue]
        env:
          PYTHONPATH: "./"